// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loglikelihood_pen
double loglikelihood_pen(Eigen::VectorXd psi, Eigen::MatrixXd X, Eigen::VectorXd y, std::vector<int> c, double sp, Eigen::MatrixXd S, size_t K, size_t psi_index);
RcppExport SEXP _adastrumm_loglikelihood_pen(SEXP psiSEXP, SEXP XSEXP, SEXP ySEXP, SEXP cSEXP, SEXP spSEXP, SEXP SSEXP, SEXP KSEXP, SEXP psi_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type sp(spSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    Rcpp::traits::input_parameter< size_t >::type K(KSEXP);
    Rcpp::traits::input_parameter< size_t >::type psi_index(psi_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_pen(psi, X, y, c, sp, S, K, psi_index));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_pen_grad
NumericVector loglikelihood_pen_grad(Eigen::VectorXd psi, Eigen::MatrixXd X, Eigen::VectorXd y, std::vector<int> c, double sp, Eigen::MatrixXd S, size_t K, size_t psi_index);
RcppExport SEXP _adastrumm_loglikelihood_pen_grad(SEXP psiSEXP, SEXP XSEXP, SEXP ySEXP, SEXP cSEXP, SEXP spSEXP, SEXP SSEXP, SEXP KSEXP, SEXP psi_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type sp(spSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    Rcpp::traits::input_parameter< size_t >::type K(KSEXP);
    Rcpp::traits::input_parameter< size_t >::type psi_index(psi_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_pen_grad(psi, X, y, c, sp, S, K, psi_index));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_pen_hess
NumericVector loglikelihood_pen_hess(Eigen::VectorXd psi, Eigen::MatrixXd X, Eigen::VectorXd y, std::vector<int> c, double sp, Eigen::MatrixXd S, size_t K, size_t psi_index);
RcppExport SEXP _adastrumm_loglikelihood_pen_hess(SEXP psiSEXP, SEXP XSEXP, SEXP ySEXP, SEXP cSEXP, SEXP spSEXP, SEXP SSEXP, SEXP KSEXP, SEXP psi_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type sp(spSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    Rcpp::traits::input_parameter< size_t >::type K(KSEXP);
    Rcpp::traits::input_parameter< size_t >::type psi_index(psi_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_pen_hess(psi, X, y, c, sp, S, K, psi_index));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adastrumm_loglikelihood_pen", (DL_FUNC) &_adastrumm_loglikelihood_pen, 8},
    {"_adastrumm_loglikelihood_pen_grad", (DL_FUNC) &_adastrumm_loglikelihood_pen_grad, 8},
    {"_adastrumm_loglikelihood_pen_hess", (DL_FUNC) &_adastrumm_loglikelihood_pen_hess, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_adastrumm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
