# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikelihood_pen <- function(psi, X, y, c, sp, S, K, psi_index) {
    .Call(`_adastrumm_loglikelihood_pen`, psi, X, y, c, sp, S, K, psi_index)
}

loglikelihood_pen_grad <- function(psi, X, y, c, sp, S, K, psi_index) {
    .Call(`_adastrumm_loglikelihood_pen_grad`, psi, X, y, c, sp, S, K, psi_index)
}

loglikelihood_pen_hess <- function(psi, X, y, c, sp, S, K, psi_index) {
    .Call(`_adastrumm_loglikelihood_pen_hess`, psi, X, y, c, sp, S, K, psi_index)
}

